[package]
name = "solana-ed25519-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
agave-feature-set = { workspace = true }
assert_matches = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { workspace = true }
solana-program-test = { workspace = true }
solana-sdk = { workspace = true }
