[package]
name = "solana-inline-spl"
description = "Limited types and ids from the Solana Program Library"
documentation = "https://docs.rs/solana-inline-spl"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["lib"]
name = "solana_inline_spl"

[dependencies]
bytemuck = { workspace = true }
solana-pubkey = { workspace = true, default-features = false, features = [
    "bytemuck",
] }

[dev-dependencies]
