[package]
name = "solana-gossip"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana-gossip"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "solana-gossip"
path = "src/main.rs"

[features]
frozen-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "solana-bloom/frozen-abi",
    "solana-ledger/frozen-abi",
    "solana-perf/frozen-abi",
    "solana-runtime/frozen-abi",
    "solana-sdk/frozen-abi",
    "solana-short-vec/frozen-abi",
    "solana-version/frozen-abi",
    "solana-vote/frozen-abi",
    "solana-vote-program/frozen-abi",
]

[dependencies]
agave-feature-set = { workspace = true }
assert_matches = { workspace = true }
bincode = { workspace = true }
bv = { workspace = true, features = ["serde"] }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
flate2 = { workspace = true }
indexmap = { workspace = true, features = ["rayon"] }
itertools = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
serde_bytes = { workspace = true }
serde_derive = { workspace = true }
siphasher = { workspace = true }
solana-bloom = { workspace = true }
solana-clap-utils = { workspace = true }
solana-client = { workspace = true }
solana-connection-cache = { workspace = true }
solana-entry = { workspace = true }
solana-frozen-abi = { version = "=2.2.1", optional = true, features = [
    "frozen-abi",
] }
solana-frozen-abi-macro = { version = "=2.2.1", optional = true, features = [
    "frozen-abi",
] }
solana-ledger = { workspace = true }
solana-logger = "=2.3.1"
solana-measure = { workspace = true }
solana-metrics = { workspace = true }
solana-net-utils = { workspace = true }
solana-perf = { workspace = true }
solana-pubkey = { version = "=2.2.1", features = ["rand"] }
solana-rayon-threadlimit = { workspace = true }
solana-rpc-client = { workspace = true }
solana-runtime = { workspace = true }
solana-sanitize = "=2.2.1"
solana-sdk = "=2.2.2"
solana-serde-varint = "=2.2.1"
solana-short-vec = "=2.2.1"
solana-streamer = { workspace = true }
solana-tpu-client = { workspace = true }
solana-version = { workspace = true }
solana-vote = { workspace = true }
solana-vote-program = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
bs58 = { workspace = true }
criterion = { workspace = true }
num_cpus = { workspace = true }
rand0-7 = { workspace = true }
rand_chacha0-2 = { workspace = true }
serial_test = { workspace = true }
solana-perf = { workspace = true, features = ["dev-context-only-utils"] }
solana-runtime = { workspace = true, features = ["dev-context-only-utils"] }
test-case = { workspace = true }

[[bench]]
name = "crds"

[[bench]]
name = "crds_gossip_pull"

[[bench]]
name = "crds_shards"

[[bench]]
name = "weighted_shuffle"
harness = false

[lints]
workspace = true
