[package]
name = "solana-net-utils"
description = "Solana Network Utilities"
documentation = "https://docs.rs/solana-net-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
name = "solana_net_utils"

[[bin]]
name = "solana-ip-address"
path = "src/bin/ip_address.rs"
required-features = ["clap"]

[[bin]]
name = "solana-ip-address-server"
path = "src/bin/ip_address_server.rs"
required-features = ["clap"]

[features]
default = []
clap = ["dep:clap", "dep:solana-logger", "dep:solana-version"]
dev-context-only-utils = []

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
clap = { version = "3.1.5", features = ["cargo"], optional = true }
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
nix = { workspace = true, features = ["socket"] }
rand = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
socket2 = { workspace = true }
solana-logger = { version = "=2.3.1", optional = true }
solana-serde = "=2.2.1"
solana-version = { workspace = true, optional = true }
tokio = { workspace = true, features = ["full"] }
url = { workspace = true }

[dev-dependencies]
solana-logger = { workspace = true }
