[package]
name = "solana-svm-example-paytube"
description = "Reference example using Solana SVM API"
version = { workspace = true }
edition = { workspace = true }
publish = false

[features]
dummy-for-ci-check = []
frozen-abi = []

[dependencies]
agave-feature-set = { workspace = true }
solana-bpf-loader-program = { workspace = true }
solana-client = { workspace = true }
solana-compute-budget = { workspace = true }
solana-logger = { workspace = true }
solana-program-runtime = { workspace = true }
solana-sdk = { workspace = true }
solana-svm = { workspace = true }
solana-system-program = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token = { workspace = true }
termcolor = { workspace = true }

[dev-dependencies]
solana-test-validator = { workspace = true }
